# Generated by Django 4.1.6 on 2023-02-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('dirección', models.CharField(max_length=30)),
                ('comuna', models.CharField(blank=True, choices=[('Rancagua', 'Rancagua'), ('Valdivia', 'Valdivia')], max_length=30)),
                ('region', models.CharField(blank=True, choices=[('OHiggins', 'OHiggins'), ('BioBio', 'BioBio'), ('Los Ríos', 'Los Ríos')], max_length=30)),
                ('pais', models.CharField(blank=True, choices=[('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Estados Unidos', 'Estados Unidos')], max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
