# Generated by Django 4.1.6 on 2023-02-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_apellidos_alter_user_dirección_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, max_length=30, verbose_name='Profesión'),
        ),
    ]
