# Generated by Django 4.1.6 on 2023-02-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telefono',
            new_name='fono',
        ),
    ]
